---
- hosts: all
  gather_facts: true
  become: yes
  become_user: root

  tasks:
    - name: Collect PCAP file from server
      fetch:
        src: /home/zamora/Documents/HOA8.1.pcap
        dest: /home/zamora/Sys3_8.1/PCAP/fetch/
        flat: yes

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Extract executable from PCAP file
      command: "tcpflow -r /home/zamora/Sys3_8.1/PCAP/fetch/HOA8.1.pcap -o /home/zamora/Sys3_8.1/PCAP/extract/"
      args:
        creates: /home/zamora/Sys3_8.1/PCAP/extract/executable.exe
    - name: Debug .exe file
      command: "cat /home/zamora/Sys3_8.1/PCAP/extract/report.xml"
      register: cat_output
      changed_when: false

    - debug:
        var: cat_output.stdout_lines
